### ISSUE TITLE
Build Failure: [[nodiscard]] attribute on friend functions causes compilation errors in Clang

### ISSUE THREAD

**Issue by utkarsh232005** [hiero-ledger/hiero-sdk-cpp#1586]
### 👾 Description of the Issue

When building the SDK on macOS (Apple Silicon / Clang), the build fails due to a syntax error in three header files. The `[[nodiscard]]` attribute is being incorrectly applied to `friend` function declarations.

**Affected Files and Reference PRs**:
- `src/sdk/main/include/AccountInfo.h` (introduced in PR #1488)
- `src/sdk/main/include/ContractFunctionResult.h` (introduced in PR #1449)
- `src/sdk/main/include/TokenNftTransfer.h` (introduced in PR #1371)

### 🔁 Steps to Reproduce

1. Clone the repository on a machine using Apple Silicon / Clang.
2. Generate the build files using the macOS preset: `cmake --preset macos-arm64-release`
3. Build the project: `cmake --build --preset macos-arm64-release`

### ✅ Expected Behavior

The project should compile successfully without any syntax errors regarding attribute placements.

### ❌ Actual Behavior

The build fails during compilation of the mentioned files because the `[[nodiscard]]` attribute cannot be placed before the `friend` keyword in a friend declaration.

Console output:
```text
src/sdk/main/include/AccountInfo.h:89:3: error: an attribute list cannot appear here
src/sdk/main/include/ContractFunctionResult.h:95:3: error: an attribute list cannot appear here
src/sdk/main/include/TokenNftTransfer.h:122:3: error: an attribute list cannot appear here
```

### 🌐 Environment

- SDK version: main (latest)
- Operating system: macOS (Apple Silicon)
- Compiler and version: Clang (Apple Clang)
- Hiero network: N/A (Build time issue)

### ✔️ Acceptance Criteria

- [ ] The described behavior is no longer reproducible
- [ ] A regression test is added that fails before the fix and passes after
- [ ] No unrelated behavior or API changes are introduced
- [ ] All existing tests continue to pass

### 🤔 Additional Information

The broken pattern looks like this:
```cpp
[[nodiscard]] friend bool operator==(const Type& lhs, const Type& rhs);
```

**Proposed Solution**:
Fix the declarations in all three files using one of these two approaches:
1. Refactor to member functions (Recommended, matches `PendingAirdropId` pattern):
```cpp
[[nodiscard]] bool operator==(const Type& other) const;
```
2. Remove the attribute from the `friend` declaration:
```cpp
friend bool operator==(const Type& lhs, const Type& rhs);
```

**Comment by rwalworth** [comment]
Thanks for the report @utkarsh232005, but I took a look and this bug doesn't exist on the current `main` branch - the three files you cited (`AccountInfo.h`, `ContractFunctionResult.h`, `TokenNftTransfer.h`) already declare `operator==` as a `[[nodiscard]] bool operator==(const T& rhs) const;` member function, which is exactly the "Recommended" fix in your own Proposed Solution. There's no `[[nodiscard]] friend` pattern anywhere under `src/sdk/main/include/` anymore.

This was fixed in #1516 (merged yesterday), which closed the original tracking issue #1496.

Could you do the following and confirm whether the build still fails?

```bash
git checkout main
git pull
cmake --preset macos-arm64-release
cmake --build --preset macos-arm64-release
```

If it builds cleanly, please go ahead and close this issue. If it still fails, please paste the **actual current** error output (file paths, line numbers, and the offending source lines from your local working copy) so we have something concrete to investigate.

One other thing worth flagging: this is an exact duplicate of #1584, which you opened and then closed yourself a couple of minutes before opening this one. If the closure of #1584 was unintentional, reopening that issue is preferable to filing a new one - keeps the discussion in one place.

**Comment by utkarsh232005** [comment]
<img width="744" height="519" alt="Image" src="https://github.com/user-attachments/assets/df6e64f7-5a64-4925-9140-9725fdad4821" />

### second screenshot


<img width="724" height="503" alt="Image" src="https://github.com/user-attachments/assets/02285b6b-11c2-4f77-9ff6-7936123bbe71" />

**Comment by rwalworth** [comment]
Thanks for the screenshots @utkarsh232005, but they actually confirm what I suspected - you're still building an old version of the code, not the current `main`.

Look at what your compiler is reporting:

```
AccountInfo.h:89:3: [[nodiscard]] friend bool operator==(const AccountInfo& lhs, const AccountInfo& rhs);
TokenNftTransfer.h:122:3: [[nodiscard]] friend bool operator==(const TokenNftTransfer& lhs, const TokenNftTransfer& rhs);
```

Those source lines do not exist on `main`. PR #1516 deleted them on 2026-05-05 and replaced them with `[[nodiscard]] bool operator==(const T& rhs) const;` member declarations.

Could you run these in your local checkout and paste the output?

```bash
cd "/Users/utkarshpatrikar/Code Files/hiero-sdk-cpp"
git remote -v
git fetch origin
git log -1 --oneline
git log -1 --oneline origin/main
sed -n '85,95p' src/sdk/main/include/AccountInfo.h
```

`git log -1 --oneline` shows the commit your working copy is on; `git log -1 --oneline origin/main` shows the latest on the remote. If those don't match, you need to update your branch (e.g. `git checkout main && git pull origin main`). The `sed` line will show what your local file actually contains for the lines the compiler is complaining about - once you're on `main`, that should print the member-function form, not the `friend` form.

If after running `git pull` you're on the latest commit and the build still fails, please paste the new error output along with `git log -1 --oneline` so we have something concrete to investigate.

**Comment by utkarsh232005** [comment]
See i am already on main branch and pulled all the changes still issue persist

<img width="1102" height="732" alt="Image" src="https://github.com/user-attachments/assets/1b7e6093-4d4a-4701-9a77-4bb881587adb" />

**Comment by rwalworth** [comment]
Found it @utkarsh232005 - look at the bottom of your terminal in the latest screenshot:

```
$ git pull origin main
From https://github.com/utkarsh232005/hiero-sdk-cpp
 * branch       main         -> FETCH_HEAD
Already up to date.
```

Your `origin` is your **fork** (`utkarsh232005/hiero-sdk-cpp`), not the upstream `hiero-ledger/hiero-sdk-cpp` repo. Your fork was created before PR #1516 was merged, and it's never been synced with upstream - so when you `git pull origin main`, you're pulling your fork's *stale* `main`, which still has the broken `[[nodiscard]] friend` code. That's why git reports "Already up to date" but the file on disk is still the old version. Very common gotcha when working with forks.

To fix it, open your fork at https://github.com/utkarsh232005/hiero-sdk-cpp, click the **"Sync fork"** button to bring it up to date with upstream, then run `git pull origin main` locally.

After that, verify with:

```bash
git log -1 --oneline
sed -n '85,95p' src/sdk/main/include/AccountInfo.h
```

You should see commit `3c1bdd7` (or something newer) and the line should read `[[nodiscard]] bool operator==(const AccountInfo& rhs) const;` - no `friend`. Then rebuild and the errors will be gone.

Going forward, it's a good habit to always have an `upstream` remote configured so you can keep your fork synced with the source repo. Let me know once you've synced - happy to keep this open until the build is working for you.

**Comment by utkarsh232005** [comment]
perfect issue is solved now and build completed successfully
thankyou for the guidance @rwalworth

**Comment by rwalworth** [comment]
Glad to hear it @utkarsh232005, and no problem! Fork-sync gotchas trip up just about everyone the first time. Welcome back any time you want to take on another contribution.
