### ISSUE TITLE
Build Failure: [[nodiscard]] attribute on friend functions causes compilation errors in Clang

### ISSUE THREAD

**Issue by utkarsh232005** [hiero-ledger/hiero-sdk-cpp#1584]
**Description**
When building the SDK on macOS (Apple Silicon / Clang), the build fails due to a syntax error in three header files. The `[[nodiscard]]` attribute is being incorrectly applied to `friend` function declarations.

**Error Message**
```text
src/sdk/main/include/AccountInfo.h:89:3: error: an attribute list cannot appear here
src/sdk/main/include/ContractFunctionResult.h:95:3: error: an attribute list cannot appear here
src/sdk/main/include/TokenNftTransfer.h:122:3: error: an attribute list cannot appear here
```

**Affected Files**
- `src/sdk/main/include/AccountInfo.h` (introduced in PR #1488)
- `src/sdk/main/include/ContractFunctionResult.h` (introduced in PR #1449)
- `src/sdk/main/include/TokenNftTransfer.h` (introduced in PR #1371)

The broken pattern looks like this in all three files:
```cpp
[[nodiscard]] friend bool operator==(const Type& lhs, const Type& rhs);
```

**Why it fails**
In C++, the `[[nodiscard]]` attribute cannot be placed before the `friend` keyword in a friend declaration. Clang strictly enforces this and rejects the syntax.

**Proposed Solution**
Fix the declarations in all three files using one of these two approaches:

1. **Refactor to member functions** (Recommended, matches `PendingAirdropId`):
```cpp
[[nodiscard]] bool operator==(const Type& other) const;
```
2. **Remove the attribute** from the `friend` declaration:
```cpp
friend bool operator==(const Type& lhs, const Type& rhs);
```

**Steps to Reproduce**
Run a CMake build on macOS with Clang:
```bash
cmake --preset macos-arm64-release
cmake --build --preset macos-arm64-release
```
